version: "3"
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  api:
    build: ./api
    ports:
      - "10000:10000"
    restart: always
    volumes:
      - ./api:/usr/src/app
    links:
      - mongodb
    depends_on:
      - mongodb
  dashboard:
    build: ./dashboard/
    ports:
      - "3000:3000"
    volumes:
      - ./dashboard:/usr/src/app
    depends_on:
      - api